name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup
      uses: jirutka/setup-alpine@v1
      with:
        branch: latest-stable
        packages: >
          doas abuild git tree wget make gcc g++ curl extra-cmake-modules 
          bluez-qt5-dev networkmanager-qt5-dev modemmanager-qt5-dev mapplauncherd-dev
          kscreenlocker-dev qt5-qtsensors-dev qt5-qtquickcontrols 
          pulseaudio-dev pkgconf xf86-input-synaptics-dev mpv-dev 
          xf86-input-libinput-dev kidletime5-dev kdecoration-dev
          libqtxdg-dev libdbusmenu-qt-dev syntax-highlighting5-dev

    - name: Initialize
      run: |
        echo "Now running as"
        whoami
        echo "" | sudo tee /etc/apk/repositories
        echo 'http://mirrors.tuna.tsinghua.edu.cn/alpine/latest-stable/main' | sudo tee -a /etc/apk/repositories
        echo 'http://mirrors.tuna.tsinghua.edu.cn/alpine/latest-stable/community' | sudo tee -a /etc/apk/repositories
        addgroup runner abuild
      shell: alpine.sh --root {0}

    - name: Build
      run: |
        echo "Now running as"
        whoami

        abuild-keygen -ain
        
        while IFS= read -r pkgs; do
          echo "Working in $pkgs..."
          cd "$pkgs"
          abuild checksum && abuild -r
          cd ..
          ls -la /home/runner/packages/lingmo-alpine-apkbuilder/x86_64/
        done < pkgs
      shell: alpine.sh {0}
    
    - name: Check
      run: |
        sudo apt install tree
        sudo tree ~/rootfs/alpine-latest-x86_64/home/runner/packages -H packages -o dirpkg.html
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        name: Release
        files: |
          dirpkg.html
          /home/runner/rootfs/alpine-latest-x86_64/etc/apk/keys/runner-*.rsa.pub
          /home/runner/rootfs/alpine-latest-x86_64/home/runner/packages/lingmo-alpine-apkbuilder/x86_64/*.apk
      