name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup
      uses: jirutka/setup-alpine@v1
      with:
        branch: v3.19
        packages: >
          doas abuild git wget make extra-cmake-modules 

    - name: Initialize
      run: |
        echo "Now running as"
        whoami
        addgroup runner abuild
      shell: alpine.sh --root {0}

    - name: Build
      run: |
        echo "Now running as"
        whoami

        abuild-keygen -ain
        
        while IFS= read -r pkgs; do
          echo "Working in $pkgs..."
          cd "$pkgs"
          abuild checksum && abuild -r
          cd ..
          ls -la /home/runner/packages/lingmo-alpine-apkbuilder/x86_64/
        done < pkgs
      shell: alpine.sh {0}
    
    - name: Check
      run: |
        sudo tree ~/rootfs/alpine-latest-x86_64/home/runner/packages -H packages -o dirpkg.html
      shell: bash

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0
        name: Release
        files: |
          dirpkg.html
          /home/runner/rootfs/alpine-latest-x86_64/etc/apk/keys/runner-*.rsa.pub
          /home/runner/rootfs/alpine-latest-x86_64/home/runner/packages/lingmo-alpine-apkbuilder/x86_64/*.apk
      