name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: alpine-latest
    permissions:
      contents: write

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        find . -type d -print0 | while IFS= read -r -d '' dir; do
          echo "Working in $dir"
          cd "$dir"
          abuild checksum && abuild -r
          cd ..
        done

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref }}
        files: |
          find . -name "*.apk"
      