name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup
      uses: jirutka/setup-alpine@v1
      with:
        branch: latest-stable
        packages: >
          abuild git wget make gcc g++ curl extra-cmake-modules 
          bluez-qt5-dev networkmanager-qt5-dev modemmanager-qt5-dev 
          kscreenlocker-dev qt5-qtsensors-dev qt5-qtquickcontrols 
          pulseaudio-dev pkgconf xf86-input-synaptics-dev mpv-dev 
          xf86-input-libinput-dev kidletime5-dev kdecoration-dev 
          kwin-dev libqtxdg-dev libdbusmenu-qt-dev syntax-highlighting5-dev

    - name: Initialize
      run: |
        echo "Now running as"
        whoami
        addgroup runner abuild
      shell: alpine.sh --root {0}

    - name: Build
      run: |
        echo "Now running as"
        whoami
        for dir in $(ls -d */ | grep -v '.github/'); do
          echo "Working in $dir..."
          cd $dir
          abuild checksum && abuild -r
          cd ..
        done
      shell: alpine.sh {0}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref }}
        files: |
          find . -name "*.apk"
      